### PR TITLE
Arm tip control

### PR DESCRIPTION
**Pull request by IanSzalai**
currently goes to a position, just the wrong one

### CODE REVIEW

**Comment by IanSzalai** [comment]
https://www.desmos.com/calculator/kwd5ynrokg

**Comment by IanSzalai** [comment]
mostly based off https://math.stackexchange.com/a/1367732

**Comment by IanSzalai** [comment]
I'm having issues trying to merge qa into this branch, @TaylerUva mind helping out?

**Comment by TaylerUva** [comment]
> I'm having issues trying to merge qa into this branch, @TaylerUva mind helping out?

Why are there so many file changes that are unrelated to the arm? Which ones are actually needed? I can set the reset the unneeded files back to match qa

**Comment by TaylerUva** [comment]
Fixed merge conflicts (had to rebase) use branch https://github.com/FRCTeam3255/Robot2023/tree/arm-tip-control-fix

**Pull request closed without merging**
